import fs from 'node:fs';
import path from 'node:path';
import type { DesignSnapshot, RuleFormat } from '../types/index.js';

/**
 * Generate AI agent rules from a design snapshot
 */
export function generateRules(
  snapshot: DesignSnapshot,
  format: RuleFormat,
): string {
  const generators: Record<RuleFormat, () => string> = {
    'cursorrules': () => generateCursorRules(snapshot),
    'claude-md': () => generateClaudeMd(snapshot),
    'agents-md': () => generateAgentsMd(snapshot),
    'copilot': () => generateCopilotInstructions(snapshot),
    'clinerules': () => generateClineRules(snapshot),
  };

  return generators[format]();
}

/**
 * Save rules to the appropriate file
 */
export function saveRules(
  projectRoot: string,
  format: RuleFormat,
  content: string,
  append: boolean = false,
): string {
  const fileMap: Record<RuleFormat, string> = {
    'cursorrules': '.cursorrules',
    'claude-md': 'CLAUDE.md',
    'agents-md': 'AGENTS.md',
    'copilot': '.github/copilot-instructions.md',
    'clinerules': '.clinerules',
  };

  const filePath = path.join(projectRoot, fileMap[format]);
  const dir = path.dirname(filePath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (append && fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, 'utf-8');
    fs.writeFileSync(filePath, existing + '\n\n' + content, 'utf-8');
  } else {
    fs.writeFileSync(filePath, content, 'utf-8');
  }

  return filePath;
}

// ─── Template generators ───────────────────────────────────

function buildTokenList(snapshot: DesignSnapshot): string {
  const colorTokens = snapshot.tokens.filter(t => t.category === 'color');
  const fontTokens = snapshot.tokens.filter(t => t.category === 'font');
  const spacingTokens = snapshot.tokens.filter(t => t.category === 'spacing');
  const radiusTokens = snapshot.tokens.filter(t => t.category === 'radius');

  const lines: string[] = [];

  if (colorTokens.length > 0) {
    lines.push('### Colors (DO NOT CHANGE)');
    const unique = [...new Set(colorTokens.map(t => `${t.property}: ${t.value}`))];
    for (const t of unique.slice(0, 30)) {
      lines.push(`- \`${t}\``);
    }
  }

  if (fontTokens.length > 0) {
    lines.push('\n### Fonts (DO NOT CHANGE)');
    const unique = [...new Set(fontTokens.map(t => `${t.property}: ${t.value}`))];
    for (const t of unique.slice(0, 15)) {
      lines.push(`- \`${t}\``);
    }
  }

  if (spacingTokens.length > 0) {
    lines.push('\n### Spacing (DO NOT CHANGE)');
    const unique = [...new Set(spacingTokens.map(t => `${t.property}: ${t.value}`))];
    for (const t of unique.slice(0, 20)) {
      lines.push(`- \`${t}\``);
    }
  }

  if (radiusTokens.length > 0) {
    lines.push('\n### Border Radius (DO NOT CHANGE)');
    const unique = [...new Set(radiusTokens.map(t => `${t.property}: ${t.value}`))];
    for (const t of unique.slice(0, 10)) {
      lines.push(`- \`${t}\``);
    }
  }

  return lines.join('\n');
}

function generateCursorRules(snapshot: DesignSnapshot): string {
  return `# Design Guard — Locked Design Tokens
# Generated by drift-guard on ${snapshot.createdAt}
# DO NOT modify these values when adding features or fixing bugs.

## CRITICAL: Design Drift Prevention

When modifying this codebase, you MUST preserve the following design tokens exactly as they are.
Do NOT change colors, fonts, spacing, or border-radius values unless explicitly asked to update the design.

If you need to add new styles, use the existing design tokens as reference.
If a design change is needed, tell the user to run \`drift-guard snapshot update\` after making the change.

${buildTokenList(snapshot)}

## Rules
1. NEVER change existing CSS color values
2. NEVER change font-family, font-size, or font-weight values
3. NEVER change margin, padding, or gap values on existing elements
4. NEVER change border-radius values
5. When adding new components, use the SAME design tokens listed above
6. If you must change a design token, warn the user first
`;
}

function generateClaudeMd(snapshot: DesignSnapshot): string {
  return `# Design Guard — Locked Design Tokens

> Generated by drift-guard on ${snapshot.createdAt}
> Run \`npx drift-guard check\` to verify design consistency

## Design Drift Prevention Rules

When working on this codebase, preserve the existing design exactly as-is.
The following design tokens are LOCKED and should NOT be modified:

${buildTokenList(snapshot)}

## Important
- Adding new features should NOT change existing visual styles
- If a CSS change affects existing components, flag it to the user
- New components should follow the same design language (colors, fonts, spacing)
- Run \`npx drift-guard check\` before committing to verify no design drift
`;
}

function generateAgentsMd(snapshot: DesignSnapshot): string {
  return `# AGENTS.md — Design Guard Rules

> Auto-generated by drift-guard. Do not edit manually.
> Snapshot: ${snapshot.createdAt} | Tokens: ${snapshot.tokens.length}

## Design Token Protection

This project uses drift-guard to prevent design drift during AI-assisted development.
The following design tokens are protected:

${buildTokenList(snapshot)}

## Agent Instructions
1. Do NOT modify existing CSS values for colors, fonts, spacing, or border-radius
2. New components MUST use the same design tokens
3. Run \`npx drift-guard check\` before suggesting commits
4. If design changes are intentional, inform the user to update the snapshot
`;
}

function generateCopilotInstructions(snapshot: DesignSnapshot): string {
  return `# Copilot Instructions — Design Guard

This project has locked design tokens. When suggesting code changes:

1. Preserve all existing CSS color, font, spacing, and border-radius values
2. Use the project's design tokens for new components
3. Do not override CSS custom properties (variables starting with --)

Protected tokens (${snapshot.tokens.length} total):

${buildTokenList(snapshot)}
`;
}

function generateClineRules(snapshot: DesignSnapshot): string {
  return `# Design Guard — Protected Design Tokens
# Generated: ${snapshot.createdAt}

DESIGN_PROTECTION=true

## Rules
- Do NOT change existing CSS values
- Preserve colors: ${snapshot.summary.color} tokens locked
- Preserve fonts: ${snapshot.summary.font} tokens locked
- Preserve spacing: ${snapshot.summary.spacing} tokens locked
- Preserve radius: ${snapshot.summary.radius} tokens locked

## Verification
Run: npx drift-guard check
Threshold: Changes to more than 10% of design tokens will be flagged

${buildTokenList(snapshot)}
`;
}
